name: release

on:
  push:
    branches:
      - dev
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/master' && 'PROD' || 'DEV' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
      
      - name: "Install dependencies"
        run: npm ci
      
      - name: "Build"
        run: npm run build

      - name: "Echo deploy env"
        run: |
         echo "Deploying to environment: ${{ job.environment }}"

      - name: Set tag version
        id: set_tag_version
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            echo "tag_version=${{ steps.version.outputs.version }}-dev" >> "$GITHUB_OUTPUT"
          else
            echo "tag_version=${{ steps.version.outputs.version }}" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.set_tag_version.outputs.tag_version }}


      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      
      - name: upload into s3
        run: |
          aws s3 cp dist/ s3://${{ vars.S3_BUCKET }} --recursive
          echo "S3 deployment complete!"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CLOUDFRONT_DIST_ID }} \
            --paths "/*"
          echo "CloudFront invalidation requested!"