name: release

on:
  push:
    branches:
      - dev
      - test
      - master
    paths:
      - .github/**
      - index.html
      - package.json
      - package-lock.json
      - ./src/**
      - public/**
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to deploy"
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/master' && 'PROD' || 'DEV' }}
    permissions:
      contents: write
    steps:

      - name: Print tag
        if: github.event.inputs.tag == ''
        run: echo "Deploying tag ${{ github.event.inputs.tag }}"

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag != '' && github.event.inputs.tag || github.ref }}
      
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
      
      - name: "Install dependencies"
        run: npm ci
      
      - name: "Build"
        run: npm run build

      - name: "Echo deploy env"
        run: |
         echo "Deploying to environment: ${{ job.environment }}"

      - name: Set tag version
        id: set_tag_version
        if: github.event.inputs.tag == ''
        run: |
          version=$(node -p "require('./package.json').version")
          echo "tag_version=$version" >> "$GITHUB_OUTPUT"

      - name: Tag version
        id: tag_version
        if:   github.event.inputs.tag == '' && github.ref == 'refs/heads/master'
        uses: mathieudutour/github-tag-action@v6.2
        with:
          default_bump: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.set_tag_version.outputs.tag_version }}


      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      
      - name: upload into s3
        run: |
          aws s3 cp dist/ s3://${{ vars.S3_BUCKET }} --recursive
          echo "S3 deployment complete!"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CLOUDFRONT_DIST_ID }} \
            --paths "/*"
          echo "CloudFront invalidation requested!"